---
title: "Homework 1 - Problem 1"
author: "Pranav Belligundu - SDS 315 UT Austin"
date: "01-23-2025"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height=3, fig.width=4, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60))
```


```{r echo = FALSE}
#libraries
library(ggplot2)
library(rvest)
library(tidyverse)
library(stringr)
```

```{r echo = FALSE}
#reading the data
profs <- read_csv('profs.csv', show_col_types = FALSE)
```


```{r echo = FALSE, message = FALSE, warnings = FALSE, fig.width=8, fig.height=5}
#Part A. Create a histogram to display the overall data distribution of course evaluation scores
ggplot(profs, aes(x = eval)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black") +
  labs(title = "Distribution of Evaluation of Professor Ratings",
       x = "Eval",
       y = "Frequency")
```

```{r echo = FALSE, message = FALSE, warnings = FALSE, fig.width=8, fig.height=5}
#Part B. Use side-by-side boxplots to show the distribution of course evaluation scores by whether or not the
#professor is a native English speaker.
ggplot(profs, aes(x = native, y = eval))+
  geom_boxplot() + 
  labs(title="Distribution of Course Evaluation based on if the Professor is a Native Speaker") +
  coord_flip()
```
```{r echo = FALSE, message = FALSE, warnings = FALSE, fig.width=8, fig.height=5}
#Part C. Use a faceted histogram with two rows to compare the distribution of course evaluation scores for male #and female instructors.
ggplot(profs, aes(x = eval)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black") +
  labs(title = "Distribution of Professor Course Evaluations",
       x = "Course Evaluations",
       y = "Frequency") +
  facet_wrap(~gender)
```

```{r echo = FALSE, message = FALSE, warnings = FALSE, fig.width=8, fig.height=5}
#Part D. Create a scatterplot to visualize the extent to which there may be an association between the
#professor’s physical attractiveness (x) and their course evaluations (y).
ggplot(profs, aes(x = beauty, y = eval)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") + # Add line of best fit
  labs(title = "Relationship between Professor’s Physical Attractiveness and Course Evaluations",
       x = "Physical Attractiveness",
       y = "Course Evaluations") +
  theme_minimal() +
  theme(legend.position = "none")

correlation <- cor(profs$beauty, profs$eval) #0.19
```


